server.port=8083

spring.application.name=item-service

# MongoDB
spring.data.mongodb.uri=mongodb+srv://nethmidileksha6_db_user:XJDn7CuoKxuORNhn@cluster0.enhq51x.mongodb.net/itemServiceDB
spring.data.mongodb.database=lost_and_found

# Config Server
spring.config.import=optional:configserver:http://localhost:8000

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

# GCS  <-- REPLACE these two values with your real GCP project info
gcs.bucket-name=your-bucket-name
gcs.project-id=your-project-id

# File upload size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always