server.port=8083
spring.application.name=ITEM-SERVICE

spring.data.mongodb.uri=mongodb+srv://admin:1234@item-service-db.arz1iut.mongodb.net/item-service-db
spring.data.mongodb.database=Lost-and-found-system

gcs.bucket-name=lostandfoundsystem
gcs.project-id=project-b4041733-aa31-4fce-9f9

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

eureka.client.service-url.defaultZone=http://34.47.225.165:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.config.import=optional:configserver:http://34.47.225.165:8000
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30