server.port=8083
server.address=0.0.0.0

spring.application.name=ITEM-SERVICE

# MongoDB
spring.data.mongodb.uri=mongodb+srv://admin:1234@item-service-db.arz1iut.mongodb.net/item-service-db
spring.data.mongodb.database=Lost-and-found-system

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# Eureka
eureka.client.service-url.defaultZone=http://34.47.225.165:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=34.47.225.165
eureka.instance.instance-id=${spring.application.name}:${random.value}

# Lease settings (optional but good)
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

# Config Server
spring.config.import=optional:configserver:http://34.47.225.165:8000